
name: DockerfileCI

on: [push]


jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
       run:  echo "$HOME/bin" >> $GITHUB_PATH

     - name: Build Docker image
       run: docker build .
 
